version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: fcamara_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - fcamara_pg_data:/bitnami/postgresql

volumes:
  fcamara_pg_data: