version: "3.7"

services:
  fcamara_database:
    image: bitnami/postgresql
    container_name: fcamara_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=fcamara
      - POSTGRES_DB=fcamara
    volumes:
      - fcamara_pg_data:/bitnami/postgresql

volumes:
  fcamara_pg_data: